import 'package:habits_second/product/constants/color_constants.dart';
import 'package:habits_second/product/constants/image_constants.dart';
import 'package:habits_second/product/constants/string_constants.dart';
import 'package:habits_second/product/models/habit_model.dart';

List<HabitModel> habitList = [
  HabitModel(
    containerColor: ColorConstants.meditation,
    habitText: StringConstants.meditate,
    imageText: ImageConstants.meditate,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.meditate,
    trailingText: 'will be adjusted',
  ),
  HabitModel(
    containerColor: ColorConstants.running,
    habitText: StringConstants.running,
    imageText: ImageConstants.running,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.running,
    trailingText: 'will be adjusted',
  ),
  HabitModel(
    containerColor: ColorConstants.readABooks,
    habitText: StringConstants.readBooks,
    imageText: ImageConstants.readBooks,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.readBooks,
    trailingText: 'will be adjusted',
  ),
  HabitModel(
    containerColor: ColorConstants.setaTodoList,
    habitText: StringConstants.setaTodoList,
    imageText: ImageConstants.setaTodoList,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.setaTodoList,
    trailingText: 'will be adjusted',
  ),
  HabitModel(
    containerColor: ColorConstants.hitTheGym,
    habitText: StringConstants.hitTheGym,
    imageText: ImageConstants.weightlifting,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.hitTheGym,
    trailingText: 'will be adjusted',
  ),
  HabitModel(
    containerColor: ColorConstants.swimming,
    habitText: StringConstants.swimming,
    imageText: ImageConstants.swimming,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.swimming,
    trailingText: 'will be adjusted',
  ),
  HabitModel(
    containerColor: ColorConstants.yoga,
    habitText: StringConstants.yoga,
    imageText: ImageConstants.yoga,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.yoga,
    trailingText: 'will be adjusted',
  ),
  HabitModel(
    containerColor: ColorConstants.cardio,
    habitText: StringConstants.cardio,
    imageText: ImageConstants.hiitCardio,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.cardio,
    trailingText: 'will be adjusted',
  ),
  HabitModel(
    containerColor: ColorConstants.cycling,
    habitText: StringConstants.cycling,
    imageText: ImageConstants.cycling,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.cycling,
    trailingText: 'will be adjusted',
  ),
  HabitModel(
    containerColor: ColorConstants.goForAWalk,
    habitText: StringConstants.goForAWalk,
    imageText: ImageConstants.goForAWalk,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.goForAWalk,
    trailingText: 'will be adjusted',
  ),
  HabitModel(
    containerColor: ColorConstants.drinkWater,
    habitText: StringConstants.drinkWater,
    imageText: ImageConstants.drinkWater,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.drinkWater,
    trailingText: 'will be adjusted',
  ),
  HabitModel(
    containerColor: ColorConstants.getGoodSleep,
    habitText: StringConstants.getGoodSleep,
    imageText: ImageConstants.getGoodSleep,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.getGoodSleep,
    trailingText: 'will be adjusted',
  ),
  HabitModel(
    containerColor: ColorConstants.takeAColdShower,
    habitText: StringConstants.takeAColdShower,
    imageText: ImageConstants.takeAColdShower,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.takeAColdShower,
    trailingText: 'will be adjusted',
  ),
  HabitModel(
    containerColor: ColorConstants.limitSugar,
    habitText: StringConstants.limitSugar,
    imageText: ImageConstants.limitSugar,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.limitSugar,
    trailingText: 'will be adjusted',
  ),
  HabitModel(
    containerColor: ColorConstants.trackCalories,
    habitText: StringConstants.trackCalories,
    imageText: ImageConstants.trackCalories,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.trackCalories,
    trailingText: 'will be adjusted',
  ),
  HabitModel(
    containerColor: ColorConstants.takeVitamins,
    habitText: StringConstants.takeVitamins,
    imageText: ImageConstants.takeVitamins,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.takeVitamins,
    trailingText: 'will be adjusted',
  ),
  HabitModel(
    containerColor: ColorConstants.eatFruits,
    habitText: StringConstants.eatFruits,
    imageText: ImageConstants.eatFruits,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.eatFruits,
    trailingText: 'will be adjusted',
  ),
  HabitModel(
    containerColor: ColorConstants.limitCaffeine,
    habitText: StringConstants.limitCaffeine,
    imageText: ImageConstants.limitCaffeine,
    subtitleText: 'will be adjusted',
    titleText: StringConstants.limitCaffeine,
    trailingText: 'will be adjusted',
  ),
];
